name: Pushover Notify (Israel Time)

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        run: python your_script.py
