name: Users Inform — Sheet Checker (every 10m)

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes
  workflow_dispatch: {}     # להרצה ידנית אם תרצה לבדוק

jobs:
  check-sheet:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Fetch CSV from Google Sheet
        id: fetch
        run: |
          curl -sSL "https://docs.google.com/spreadsheets/d/e/2PACX-1vS62g9OlDEDwyzAxPX6kv7BI5Y8B_U5Y37YgkcyWq2GJTdceBipvGuHJxbVHnZDa2gWZU7nUcH07TK6/pub?gid=0&single=true&output=csv" -o sheet.csv
          echo "CSV downloaded"

      - name: Parse CSV and detect V/v in 'update' column
        id: parse
        run: |
          matches=$(awk -F',' 'tolower($0) ~ /,v($|,)/' sheet.csv | wc -l)
          echo "matches=$matches" >> $GITHUB_OUTPUT
          echo "Found $matches rows with V/v in update field"

      - name: Trigger bot workflow (if matches > 0)
        if: steps.parse.outputs.matches != '0'
        run: |
          echo "Dispatching run-users-inform-bot.yml..."
          gh api repos/${{ github.repository }}/dispatches \
            --field event_type=users_inform_trigger \
            --field client_payload:='{}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
